image:
  file: dockerfile

tasks:
  - name: RASA Server
    command: |
      cd rasa && rasa shell

  - name: RASA SDK Actions
    command: |
      cd && rasa run actions

  - name: Gradle Build
    command: |
      cd rasa4jaca && docker build -t agents .

vscode:
  extensions:
    - ms-python.python
    - redhat.java
    - GabrielBB.vscode-lombok

ports:
  - port: 5055
    visibility: public
  - port: 3272
    onOpen: open-preview
  - port: 8080
    visibility: public
  - port: 5005
    visibility: public
  - port: 5006
    visibility: public
  - port: 5007
    visibility: public
  - port: 5008
    visibility: public

