tasks:
  - before: docker-compose build
  - command: cd rasa && docker build -t my-rasa-bot . 

vscode:
  extensions:
     - https://open-vsx.org/api/tabajara-krausburg/jacamo4code/1.2.1/file/tabajara-krausburg.jacamo4code-1.2.1.vsix
     - redhat.vscode-xml

image: gitpod/workspace-full

ports:
  - port: 5055
    visibility: public
  - port: 3272
    onOpen: open-preview
  - port: 8080
    visibility: public
  - port: 5005
    visibility: public
  - port: 5006
    visibility: public
  - port: 5007
    visibility: public
  - port: 5008
    visibility: public

