tasks:
  - command: docker-compose build && docker-compose up 

vscode:
  extensions:
     - https://open-vsx.org/api/tabajara-krausburg/jacamo4code/1.2.1/file/tabajara-krausburg.jacamo4code-1.2.1.vsix
     - redhat.vscode-xml

image: gitpod/workspace-full

