image:
  file: dockerfile

tasks:
  - name: Chatbot 1
    command: |
      cd rasa && rasa shell -p 5005

  - name: Chatbot 2
    command: |
      cd rasa && rasa shell -p 5006

  - name: Chatbot 3
    command: |
      cd rasa && rasa shell -p 5007

  - name: Chatbot 4
    command: |
      cd rasa && rasa shell -p 5008

  - name: RASA SDK Actions
    command: |
      cd rasa && rasa run actions

  - name: Gradle Build
    command: |
      cd rasa4jaca && gradle build && gradle run
vscode:
  extensions:
    - ms-python.python
    - redhat.java
    - GabrielBB.vscode-lombok

ports:
  - port: 5055
    visibility: public
  - port: 3272
    onOpen: open-browser
  - port: 8080
    visibility: public
  - port: 5005
    visibility: public
  - port: 5006
    visibility: public
  - port: 5007
    visibility: public
  - port: 5008
    visibility: public

