tasks:
  - before: python -m pip install --upgrade pip rasa[spacy]
  - command: docker-compose build && docker-compose up

vscode:
  extensions:
     - https://open-vsx.org/api/tabajara-krausburg/jacamo4code/1.2.1/file/tabajara-krausburg.jacamo4code-1.2.1.vsix
     - redhat.vscode-xml

image: gitpod/workspace-full-vnc
ports:
  - port: 6080
    onOpen: open-preview