image:
  file: dockerfile

tasks:
  - name: Maria
    command: |
      cd rasa && rasa shell -p 5005

  - name: thiago
    command: |
      cd rasa && rasa shell -p 5005

  - name: otto
    command: |
      cd rasa && rasa shell -p 5005

  - name: heridiotes
    command: |
      cd rasa && rasa shell -p 5005

  - name: RASA SDK Actions
    command: |
      cd rasa && rasa run actions

  - name: Gradle Build
    command: |
      cd rasa4jaca && gradle build
vscode:
  extensions:
    - ms-python.python
    - redhat.java
    - GabrielBB.vscode-lombok

ports:
  - port: 5055
    visibility: public
  - port: 3272
    onOpen: open-browser
  - port: 8080
    visibility: public
  - port: 5005
    visibility: public
  - port: 5006
    visibility: public
  - port: 5007
    visibility: public
  - port: 5008
    visibility: public

