tasks:
  - init: cd rasa && docker build -t my-rasa-bot . && docker run -it -p 5005:5005 my-rasa-bot

vscode:
  extensions:
     - https://open-vsx.org/api/tabajara-krausburg/jacamo4code/1.2.1/file/tabajara-krausburg.jacamo4code-1.2.1.vsix
     - redhat.vscode-xml

image: gitpod/workspace-full

