
services:
  action_server:
    build:
      context: ./rasa/actions
    image: my-rasa-actions
    ports:
      - "5055:5055"
    volumes:
      - ./rasa/actions:/app/actions
    command: >
      start --actions actions
    networks:
      - rasa-network

  rasa4jaca:
    build: 
      context: ./rasa4jaca
    image: dial4jaca-image  # Replace this with the actual Docker image for dial4jaca
    ports:
      - "8080:8080"
      - "3272:3272"
    networks:
      - rasa-network

networks:
  rasa-network:
    driver: bridge
